// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// eigen_sample_X
Rcpp::List eigen_sample_X(Rcpp::NumericMatrix& YY, Rcpp::NumericMatrix& XX, Rcpp::NumericVector& WW, Rcpp::NumericMatrix& SS, Rcpp::NumericMatrix& AA, Rcpp::NumericMatrix& BB);
RcppExport SEXP _cmcca_eigen_sample_X(SEXP YYSEXP, SEXP XXSEXP, SEXP WWSEXP, SEXP SSSEXP, SEXP AASEXP, SEXP BBSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type YY(YYSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type XX(XXSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type WW(WWSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type SS(SSSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type AA(AASEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type BB(BBSEXP);
    rcpp_result_gen = Rcpp::wrap(eigen_sample_X(YY, XX, WW, SS, AA, BB));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cmcca_eigen_sample_X", (DL_FUNC) &_cmcca_eigen_sample_X, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_cmcca(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
