# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eigen_sample_X <- function(YY, XX, WW, SS, AA, BB) {
    .Call(`_cmcca_eigen_sample_X`, YY, XX, WW, SS, AA, BB)
}

